plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt' // BNRG ch 12.8
    id 'androidx.navigation.safeargs' // BNRG ch 13.10
}

android {
    namespace 'edu.vt.cs5254.dreamcatcher'
    compileSdk 33

    defaultConfig {
        applicationId "edu.vt.cs5254.dreamcatcher"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: 'true' // P2B testing

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation": "$projectDir/schemas".toString(),
                ]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding = true
        // allows association btwn fragment_dream_detail.xml and DreamDetailFragment.kt
    }
    testOptions {
        execution 'ANDROIDX_TEST_ORCHESTRATOR' // for P2B Testing
        animationsDisabled = true
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation 'androidx.fragment:fragment-ktx:1.5.5' // BNRG ch 9
    debugImplementation 'androidx.fragment:fragment-testing:1.5.5' // BNRG ch 9 challenge
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0' // BNRG ch 10
    implementation 'androidx.recyclerview:recyclerview:1.3.0' // BNRG ch 10
    implementation 'androidx.test.espresso:espresso-contrib:3.5.1' // DLF tests (not in BNRG!)

//    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4' // BNRG ch 12.1 TEMPORARY
//    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4' // BNRG ch 12.1 TEMPORARY
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.0' // BNRG ch 12.1
    implementation 'androidx.room:room-runtime:2.5.0' // BNRG ch 12.8
    implementation 'androidx.room:room-ktx:2.5.0' // BNRG ch 12.8
    kapt 'androidx.room:room-compiler:2.5.0' // BNRG ch 12.8

    implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3' // BNRG ch 13
    implementation 'androidx.navigation:navigation-ui-ktx:2.5.3' // BNRG ch 13

    androidTestImplementation 'androidx.test:runner:1.5.2' // for P2B Testing
    androidTestUtil 'androidx.test:orchestrator:1.4.2' // for P2B Testing

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}